version: '3.7'
services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: dweather
            MONGO_INITDB_ROOT_PASSWORD: dweather
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
    dweather-telegram-bot:
        build: ./dweather-telegram-bot/
        depends_on:
            - dweather-core
    dweather-core:
        build: ./dweather-core/
        ports:
            - 8080:8080
        depends_on:
            - mongodb

volumes:
    mongodb_data_container: