dweather:
    command:
        selection:
            events: 'Your events:'
            precipitation: 'Select desired precipitation:'
            temperature: 'Select desired temperature interval:'
            wind: 'Select desired wind interval:'
    api:
        url: http://dweather-core:8080/v1/dweather/events
server:
    port: 8081
